#:schema node_modules/wrangler/config-schema.json
name = "remix-trpc-fun-frontend"
compatibility_date = "2024-10-04"

main = "./build/worker/index.js"

assets = { directory = "./build/client" }

[[services]]
binding = "TRPC_BACKEND"
service = "remix-trpc-fun-backend"

[[env.staging.services]]
binding = "TRPC_BACKEND"
service = "remix-trpc-fun-backend-staging"

[[env.production.services]]
binding = "TRPC_BACKEND"
service = "remix-trpc-fun-backend-production"


